services:
  - type: web
    name: liar-game
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: HOST_CODE
        value: BOM
